FlaskBlogPro/App/views.py
# url+视图函数
import datetime
import io
import random
import re
import uuid
from PIL import Image as Img,ImageDraw,ImageFont
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, make_response
from sqlalchemy import desc

from App.exts import cache
from .models import *

blog = Blueprint('blog', __name__)
admin = Blueprint('admin', __name__)


@blog.route('/')
def home():
    return 'HOME'

# 主界面
@blog.route('/index/',methods=["GET","POST"])
def index():
    if request.method == "GET":

        user = User.query.get(1)
        imgs = Image.query.all()
        types = Articletype.query.all()

        dlog = Article.query.all()
        data = {
            "user":user,
            "imgs":imgs,
            "types":types,
            "dlog":dlog,
        }
        return render_template('blog/index.html',**data)

    elif request.method == "POST":
        typeid = None
        try:
            typeid = int(request.form.get("typeid"))
        except:
            return "参数有误"
        dlog = Articletype.query.get(typeid).articles

        articlelist = []
        for i in dlog:
            articlelist.append({"id":i.id,"userid":i.userid,"title":i.title,
            "msg":i.msg,"imgpath":i.imgpath,"type":i.type,
            "isshadow":i.isshadow,"status":i.status,
            "readnum":i.readnum,"zan":i.zan,})

        data = {
            "code":1,
            "msg":"success",
            "data":articlelist,
        }
        return jsonify(data)



# 相册界面
@blog.route('/share/',methods=["GET","POST"])
def share():
    if request.method == "GET":


        return render_template('blog/share.html')

    elif request.method == "POST":
        # 默认就是只有1号 取1号的信息
        page = 1
        try:
            page = int(request.form.get("page"))
        except:
            page = 1
        per_page = 8
        imgs = Image.query.paginate(page, per_page, error_out=False)
        print(imgs.pages)
        imglist = []
        for i in imgs.items:
            imglist.append(
                {"id": i.id, "title": i.title, "userid": i.userid,
                 "path": i.path, "detail": i.detail, "time": i.time}
            )
        data = {
            "code": 1,
            "msg": "success",
            "data": {
                "data":imglist,
                "pages":imgs.pages,
                "page":imgs.page,
                "has_prev": imgs.has_prev,
                "has_next": imgs.has_next,

            }
        }
        return jsonify(data)



# 我的日记界面
@blog.route('/list/',methods=["GET","POST"])
def list():
    if request.method == "GET":
        user = User.query.get(1)
        imgs = Image.query.all()
        types = Articletype.query.all()  # 文章类型
        dlog = Article.query.filter(Article.type==2)  # type==2为查询日记
        paihang = Article.query.filter().order_by(desc("readnum")).limit(8)  # 所有文章按点击排行，也就是阅读量排行
        biaoqian = Articlelabel.query.filter().limit(8)  # 标签只取8个
        data = {
            "user": user,
            "types": types,
            "dlog": dlog,
            "paihang":paihang,
            "biaoqian":biaoqian,
        }
        return render_template('blog/list.html',**data)

    elif request.method == "POST":
        pass



# 关于我界面
@blog.route('/about/',methods=["GET","POST"])
def about():
    if request.method == "GET":
        user = User.query.get(1)
        imgs = Image.query.all()
        types = Articletype.query.all()
        data = {
            "user":user,
            "imgs":imgs,
            "types":types,

        }

        return render_template('blog/about.html',**data)

    elif request.method == "POST":
        pass


# 留言界面
@blog.route('/gbook/',methods=["GET","POST"])
def gbook():
    if request.method == "GET":
        user = User.query.get(1)
        imgs = Image.query.all()
        types = Articletype.query.all()
        liuyan = Lmessage.query.filter().order_by(desc("time"))
        data = {
            "user": user,
            "imgs": imgs,
            "types": types,
            "liuyan":liuyan,
        }

        return render_template('blog/gbook.html',**data)

    elif request.method == "POST":
        name = request.form.get("name")
        email = request.form.get("email")
        msg = request.form.get("msg")
        if name and email and msg:
            lmsg = Lmessage()  # 建立新的留言
            lmsg.name = name
            lmsg.email = email
            lmsg.msg = msg
            lmsg.time = datetime.datetime.now()
            db.session.add(lmsg)
            db.session.commit()
            liuyan = Lmessage.query.filter().order_by(desc("time"))
            llist = []   # 重新返回留言信息
            for i in liuyan:
                llist.append({"name":i.name,"msg":i.msg,
                              "time":i.time,"msgback":i.msgback,})

            return jsonify(data={"code": 1, "msg": "success", "data": llist})
            # return redirect(url_for("blog.gbook"))  # 重定向不会弄
        else:
            return jsonify(data = {"code": 0,"msg": "error","data": []})


# 内容页面界面1
@blog.route('/info/<re("(\d)*"):id>',methods=["GET","POST"])
def info(id=1):
    try:
        id = int(id)
    except:
        id = 1
    if request.method == "GET":

        user = User.query.get(1)
        types = Articletype.query.all()  # 文章类型
        paihang = Article.query.filter().order_by(desc("readnum")).limit(8)  # 所有文章按点击排行，也就是阅读量排行
        biaoqian = Articlelabel.query.filter().limit(8)  # 标签只取8个
        article = Article.query.get(id)
        article.readnum+=1
        comts = Comment.query.filter(Comment.articleid==id)
        comments = []
        for i in comts:
            comments.append({"name":i.name,"msg":i.msg,"time":i.time,})
        list = []
        lanmu = ""
        if article.type:  # 如果文章类型存在
            lanmu = Articletype.query.get(article.type).title  # 则写道lanmu中
        al = Alabel.query.filter(Alabel.articleid == article.id)  # 在三方表中查找标签集
        for j in al:  # 遍历查找到的标签集
            lab = Articlelabel.query.get(j.labelid)  # 把标签集里的标签id放入
            if lab:  # 如果标签存在
                list.append(lab.labelname)
        data = {
            "user": user,
            "types": types,
            "paihang": paihang,
            "biaoqian": biaoqian,
            "comments": comments,
            "article":{"articleid": article.id, "lanmu": lanmu, "labels": list,"article": article, },
        }
        db.session.commit()
        return render_template('blog/info.html',**data)

    elif request.method == "POST":
        zanid = request.form.get("zan")
        username = request.form.get("username")
        key = request.form.get("key")
        saytext = request.form.get("saytext")


        if key:
            if not (key.lower() == (cache.get(request.remote_addr+"vcode")).lower()):
                return "验证码错误"
        elif key=="":
            return "验证码错误"
        if username and key and saytext:
            if key.lower() == (cache.get(request.remote_addr+"vcode")).lower():
                comment = Comment()
                comment.articleid=id
                comment.name = username
                comment.msg = saytext
                comment.time = datetime.datetime.now()
                db.session.add(comment)
                db.session.commit()
                return redirect("/info/%s"%id)
            else:
                return "验证码错误"

        try:
            if zanid:
                zanid = int(zanid)
        except:
            zanid = None
        if zanid and not (username or key or saytext):
            if not cache.get(request.remote_addr+"zan"):
                cache.set(request.remote_addr+"zan",[])
            ca = cache.get(request.remote_addr+"zan")
            if id not in ca:
                article = Article.query.get(zanid)
                article.zan += 1
                db.session.commit()
                ca.append(id)

                cache.set(request.remote_addr+"zan",ca,timeout=60*60*24)   # 设置一个ip一天只能赞一篇文章一次
            else:
                return "一天只能赞一次哦"

        return "ok"


# 内容页面界面2
@blog.route('/infopic/',methods=["GET","POST"])
def infopic():
    if request.method == "GET":
        return render_template('blog/infopic.html')

    elif request.method == "POST":
        pass




# --------------------------------------管理员--------------------------------------------  #


# 管理登录
@admin.route('/admin/login/',methods=["POST","GET"])
def admin_login():
    if request.method == "GET":
        return render_template('admin/login.html')
    elif request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        adm = Admin.query.filter(Admin.username==username,Admin.password==password).first()
        if adm:
            token = request.cookies.get("token")
            tok = AdminToken.query.filter(AdminToken.admin == adm.id).first()
            res = redirect(url_for("admin.admin_index"))
            if tok:
                uid = uuid.uuid4().hex
                tok.token = uid
                tok.outtime = (datetime.datetime.now()+datetime.timedelta(days=1))
                res.set_cookie("token",uid,max_age=60*60*24)
                db.session.commit()

            else:
                tok = AdminToken()
                tok.admin = adm.id
                tok.token = uuid.uuid4().hex
                tok.outtime = (datetime.datetime.now() + datetime.timedelta(days=1))
                res.set_cookie("token",str(tok.token),max_age=60*60*24)
                print(tok,type(tok))
                db.session.add(tok)
                db.session.commit()
            return res

        else:
            data = {
                "error":"输入的账号或密码有误",
            }
            return render_template('admin/login.html',**data)


# 管理首页
@admin.route('/admin/index/')
def admin_index():
    return render_template('admin/index.html')


# 文章管理
@admin.route('/admin/article/<int:num>/',methods=["POST","GET"])
def admin_article(num):

FlaskBlogPro/App/templates/blog/about.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/blog/css/base.css" rel="stylesheet">
<link href="/static/blog/css/index.css" rel="stylesheet">
<link href="/static/blog/css/m.css" rel="stylesheet">
<script src="/static/blog/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/blog/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/blog/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
{% include 'blog/header.html' %}
<article>
  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
          <i><img src="{{ user.icon }}"></i>
          <p><b>{{ user.name }}</b>，{{ user.sign }}</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        {% for i in range(6) %}
                 <li><a href="/"><img src="{{ imgs[i].path }}"></a></li>
        {% endfor %}
      </ul>
    </div>
    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei" id="fenlei">
      <h2>文章分类</h2>
      <ul>
        {% for type in types %}
                 <li typeid="{{ type.id }}"><a href="javascript:;">{{ type.title }}({{ type.articles | length }})</a></li>
        {% endfor %}
      </ul>
    </div>
   
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/blog/images/wx.jpg">
      </ul>
    </div>
  </aside>
  <main class="r_box" id="r_box">
     <div class="about">
      {{ user.msg | safe }}
     </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>

<script>
    $("#fenlei li").click(function () {
        typeid = $(this).attr("typeid");

        $.post("/index/",{"typeid":typeid},function (data) {

            list = data.data;
            lis = "";
            for(var i=0;i<list.length;i++){
                lis += "<li><i><a href='/info/"+list[i]['id']+"'><img src='"+list[i]['imgpath']+"'></a></i><h3><a href='/info/"+list[i]['id']+"'>"+list[i]['title']+"</a></h3> <p>"+list[i]['msg']+"</p></li>";

            }
            $("#r_box").html(lis);
        })
    });

</script>
</body>
</html>

FlaskBlogPro/App/templates/blog/gbook.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/blog/css/base.css" rel="stylesheet">
<link href="/static/blog/css/index.css" rel="stylesheet">
<link href="/static/blog/css/m.css" rel="stylesheet">
<script src="/static/blog/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/blog/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/blog/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
{% include 'blog/header.html' %}
<article>
  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
          <i><img src="{{ user.icon }}"></i>
          <p><b>{{ user.name }}</b>，{{ user.sign }}</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        {% for i in range(6) %}
                 <li><a href="/"><img src="{{ imgs[i].path }}"></a></li>
        {% endfor %}
      </ul>
    </div>
     <div class="search">
      <form action="/static/blog//e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei" id="fenlei">
      <h2>文章分类</h2>
      <ul>
        {% for type in types %}
                 <li typeid="{{ type.id }}"><a href="javascript:;">{{ type.title }}({{ type.articles | length }})</a></li>
        {% endfor %}
      </ul>
    </div>
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/blog/images/wx.jpg">
      </ul>
    </div>
  </aside>
<main class="r_box" id="r_box">
    <div class="gbook">
    <div>
        {% for i in liuyan %}
            <div class="fb">
                <ul>
                  <p class="fbtime"><span> {{ i.time }} </span> {{ i.name }}</p>
                  <p class="fbinfo">{{ i.msg }}</p>
                </ul>
            </div>
            {% if i.msgback %}
                 <div class="hf">
                    <ul>
                      <p class="zzhf"><font color="#FF0000">站长回复:</font>{{ i.msgback }}</p>
                    </ul>
                </div>
            {% endif %}

        {% endfor %}
    </div>
          <div class="gbox">
            <form action="" method="post">
              <p> <strong>来说点儿什么吧...</strong></p>
              <p><span> 您的姓名:</span>
                <input name="name" type="text" id="name" >
                *</p>
              <p><span>联系邮箱:</span>
                <input name="email" type="text" id="email">
                *</p>
              <p><span class="tnr">留言内容:
              </span>
                <textarea name="lytext" cols="60" rows="12" id="lytext"></textarea>
              </p>
              <p>
                <input type="submit" id="submit" value="提交">
                <input name="enews" type="hidden" id="enews" value="AddGbook">
              </p>
            </form>
          </div>
    </div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>

<script>
    $("#fenlei li").click(function () {
        typeid = $(this).attr("typeid");

        $.post("/index/",{"typeid":typeid},function (data) {

            list = data.data;
            lis = "";
            for(var i=0;i<list.length;i++){
                lis += "<li><i><a href='/info/"+list[i]['id']+"'><img src='"+list[i]['imgpath']+"'></a></i><h3><a href='/info/"+list[i]['id']+"'>"+list[i]['title']+"</a></h3> <p>"+list[i]['msg']+"</p></li>";

            }
            $("#r_box").html(lis);
        })
    });
    $("#submit").click(function () {
        $.post("/gbook/",{"name":$("#name").val(),"email":$("#email").val(),"msg":$("#lytext").val()},function (data) {
            if(data.data.code)
                if (data.data.code == 0){
                    $(".tnr").eq(0).html("留言内容:<b style='color:red'>名字和邮箱和内容要输入哦~</b>")
                }


            if (data.data.code == 1){
                $("#name").val("");
                $("#email").val("");
                $("#lytext").val("");
                $(".gbook>div").eq(0).html("");
                var div = "";
                var dataa = data.data.data;
                for(var i=0;i<dataa.length;i++){
                    div +="<div class=\"fb\">\n" +
                    "            <ul>\n" +
                    "              <p class=\"fbtime\"><span> "+dataa[i].time+"</span> "+dataa[i].name+"</p>\n" +
                    "              <p class=\"fbinfo\">"+dataa[i].msg+"</p>\n" +
                    "            </ul>\n" +
                    "        </div>";
                    if (dataa[i].msgback){
                        div += "<div class=\"hf\">\n" +
                            "                <ul>\n" +
                            "                  <p class=\"zzhf\"><font color=\"#FF0000\">站长回复:</font>"+dataa[i].msgback+"</p>\n" +
                            "                </ul>\n" +
                            "            </div>"
                    }

                }
                $(".gbook>div").eq(0).html(div);
                alert("留言成功")
            }

            window.location.replace("/gbook/")
        });
        return false;
    })
</script>
</body>
</html>

FlaskBlogPro/App/templates/blog/header.html
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">杨青个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{{ url_for('blog.index') }}">网站首页</a></li>
      <li><a href="{{ url_for('blog.share') }}">我的相册</a></li>
      <li><a href="{{ url_for('blog.list') }}">我的日记</a></li>
      <li><a href="{{ url_for('blog.about') }}">关于我</a></li>
      <li><a href="{{ url_for('blog.gbook') }}">留言</a></li>
      <li><a href="/info/">内容页</a></li>
      <li><a href="{{ url_for('blog.infopic') }}">内容页</a></li>
    </ul>
</nav>
</header>

<script>
    $(function () {
        var as = $("#starlist a");
        for(var i=0;i<as.length;i++){
            str = new RegExp(as.eq(i).attr("href"));
            if (str.test(window.location.pathname)){
                as.eq(i).addClass("selected")
            }
        }

    })
</script>

FlaskBlogPro/App/templates/blog/index.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="/static/blog/css/base.css" rel="stylesheet">
<link href="/static/blog/css/index.css" rel="stylesheet">
<link href="/static/blog/css/m.css" rel="stylesheet">
<script src="/static/blog/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/blog/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/blog/js/modernizr.js"></script>
<![endif]-->
</head>
<body>
{% include 'blog/header.html' %}

<article>
  <aside class="l_box" >
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="{{ user.icon }}"></i>
          <p><b>{{ user.name }}</b>，{{ user.sign }}</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
            {% for i in range(6) %}
                 <li><a href="/"><img src="{{ imgs[i].path }}"></a></li>
            {% endfor %}

        </ul>
      </div>
      <div class="search">
        <form action="" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei" id="fenlei">
        <h2>文章分类</h2>
        <ul>
            {% for type in types %}
                 <li typeid="{{ type.id }}"><a href="javascript:;">{{ type.title }}({{ type.articles | length }})</a></li>
            {% endfor %}
        </ul>
      </div>
      <div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
        </ul>
      </div>
      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="http://www.yangqq.com">杨青个人博客</a> <a href="http://www.yangqq.com">杨青博客</a>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="{{ user.QRcode }}">
        </ul>
      </div>
  </aside>
  <main class="r_box" id="r_box">
    {% for log in dlog %}
        <li>
                <i><a href="/info/{{ log.id }}"><img src="{{ log.imgpath }}"></a></i>
              <h3><a href="/info/{{ log.id }}">{{ log.title }}</a></h3>
              <p>{{ log.msg }}</p>
        </li>
    {% endfor %}
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>

<script>
    $("#fenlei li").click(function () {
        typeid = $(this).attr("typeid");

        $.post("/index/",{"typeid":typeid},function (data) {

            list = data.data;
            console.log(list)
            lis = "";
            for(var i=0;i<list.length;i++){
                lis += "<li><i><a href='/info/"+list[i]["id"]+"'><img src='"+list[i]['imgpath']+"'></a></i><h3><a href='/info/"+list[i]["id"]+"'>"+list[i]['title']+"</a></h3> <p>"+list[i]['msg']+"</p></li>";

            }
            $("#r_box").html(lis);
        })
    });

</script>
</body>
</html>